export const projects = [
    {
        id: '1',
        name: "El Morssi Abo El Abbas Mosque",
        location: "Alexandria, Egypt",
        category: "Heritage",
        industry: "Religious and cultural Heritage",
        // client: "-",
        services: ["3D Laser Scanning"],
        deliverables: ["Pointcloud", "As-Built 2D drawings"],
        challange: "Morsi Abl Elabbas mosque domes and walls covered with detailed patterns. Traditional measuring tapes and standard images cannot document them accurately.",
        solution: "we used advanced laser scanners that act like a digital eye, captures millions of points per second, ensuring high quality pointcloud that shows every ornament and pieces that needs to be repaired.",
        image: "/images/almorssimosque.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '2',
        name: "Saudi Consulate",
        location: "Alexandria, Egypt",
        category: "Heritage",
        industry: "Heritage with national significance",
        // client: "Al Rowad Modern Engineering",
        services: ["Pointcloud", "3D Model", "As-built 2D drawings"],
        deliverables: ["3D Point Cloud", "High Detailed 3D Model", "2D AutoCAD Drawings (Site, Plans & Elevations)"],
        challange:"An Old heritage building with delicate structure and hard accessibility, also, filled with carvings and ornaments, required conducting surveying for documention and restoration.",
        solution:"Using different types of laser scanners to map every inch without physically touching a single ancient stone, capturing the ornaments with high density to show cracks and ornaments to deliver a high quality 3D model and 2D drawings.",
        image: "/images/saudiconsulate.jpg",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '3',
        name: "Knauf Gypsum Factory",
        location: "Suez, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/knauf.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '4',
        name: "Movenpick",
        location: "Ain Sokhna, Egypt",
        category: "Architecture",
        industry: "Architecture",
        // client: "GALALAH CO.",
        services: ["3D Laser Scanning for Documentation and Renovation"],
        deliverables: ["3D Revit Model", "2D Drawings for hotel buildings (floor plans, ceiling plans, furniture layouts , sections, site plan)"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/movenpick.jpg",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '5',
        name: "Steel Warehouse",
        location: "Ain Sokhna, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "DP world",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud", "3D BIM Model with MEP Systems", "2D AutoCAD Drawings (Floor Plan- 4 internal Sections)"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/steelwarehouse.jpg",
        videoUrl: "",
    },
    {
        id: '6',
        name: "Monorail",
        location: "Cairo, Egypt",
        category: "Architecture",
        industry: "Transportation",
        // client: "Hill International",
        services: ["3D Scanning", "3D As-Built BIM Modeling"],
        deliverables: ["3D Point Cloud", "3D Revit Model for As-Built Concrete and Steel Works"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/monorail.jpg",
        videoUrl: "",
    },
    {
        id: '7',
        name: "Alexandria Main Post Office",
        location: "Alexandria, Egypt",
        category: "Architecture",
        industry: "Architecture",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point cloud", "3D Revit model", "2D AutoCAD plans", "Façade drawings"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/alexpost.png",
        videoUrl: "",
    },
    {
        id: '8',
        name: "Cotton Bourse",
        location: "Alexandria, Egypt",
        category: "Heritage",
        industry: "Industrial Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["Pointcloud", "2D as-built drawings"],
        challange: "An ancient decaying building that had been neglected with delicate structure, capturing and turning it into clean 2D drawings that a construction team can use is a massive challenge.",
        solution: "Using different scanners to capture several areas with different accuracies and deliver 2D drawings for the building that provide enough details for making restoration and rehabilitation decisions.",
        image: "/images/cottonbourse.jpg",
        videoUrl: "",
    },
    {
        id: '9',
        name: "Davies and Metropolitan",
        location: "Luxor, Egypt",
        category: "Heritage",
        industry: "Modern Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["Pointcloud", "3D models", "2D As-built drawings"],
        challange: "Two buildings build by the American delegation and by the polish delegation for decades, with a complex and irregular shape and floors required full surveying and documentation, A traditional method cannot fulfill this hard mission.",
        solution: "Using laser scanners to see through the complexity and capture each building in one unified pointcloud that allows us create a detailed 3D model and 2D drawings for all elements even the irregular ones and extract any other data needed for documentation.",
        image: "/images/davies.jpg",
        videoUrl: "",
    },
    {
        id: '10',
        name: "Sporting Club",
        location: "Alexandria, Egypt",
        category: "Heritage",
        industry: "Social/Recreational Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["Pointcloud", "3D Model"],
        challange: "Sporting stadium in Alexandria, A stadium that wasn’t just big; it was a complex maze with overlapping multilevels and many stairs, traditional method like measuring tapes or manual scanners were physically impossible to use.",
        solution: "We didn’t just capture this complex 3D puzzle but also created a detailed 3D model. Using Mobile SLAM technology to scan through the building, mapping every detail and capturing all the different levels then using the generated pointcloud to create a 3D digital twin that can be navigated throw to understand the shape and form of this building.",
        image: "/images/sporting.png",
        videoUrl: "",
    },
    {
        id: '11',
        name: "Sahuraa Pyramid",
        location: "Giza, Egypt",
        category: "Heritage",
        industry: "Archaeological Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["Pointcloud", "3D Model"],
        challange: "The excavation is a delicate and fluid process ,ensuring the safety of the structure and the accuracy of the finds is needed, Also, the interior of the pyramid is pitch black and extremely cramped, neither the traditional ways or the heavy big equipment can help monitoring this hard process.",
        solution: "Using our lightweight, portable 3D Laser scanners that could be carried deep to the pyramid’s heart capturing every stone and recording the “before and after” , providing the mission with a “perfect diary” of their progress and also a 3D model for the inside chambers of the pyramid.",
        image: "/images/sahuraa.jpg",
        videoUrl: "",
    },
    {
        id: '12',
        name: "College Saint Marc",
        location: "Alexandria, Egypt",
        category: "Heritage",
        industry: "Industrial Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud", "2D As-Built Drawings"],
        challange: "A massive Educational institution with busy sechdule ,and high students traffic, surveying for the entire campus and ,a church with highly detailed ornaments could only be ,conducted in one weekend before the bells rang.",
        solution: "with good planning everything is possible. with our high-speed ,scanning team, our smart strategy and good coordination, we used multiple ,Laser scanners to scan the whole campus in just one day, then delivered the 2D ,drawings in no time.",
        image: "/images/saintmarc.png" ,
        videoUrl: "",
    },
    {
        id: '13',
        name: "Abydos Temple of Seti I",
        location: "Sohag, Egypt",
        category: "Heritage",
        industry: "Sacred Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud"],
        challange: "A building from the ancient civilization, with many chambers, dark corners, carvings on walls and complex form. Traditional methods and standard photography will take forever to document this ancient masterpiece.",
        solution: "we conducted the surveying with our high quality laser 3D scanners and SLAM technology to cover every inch and stone with at most speed and delivered a high density colorized pointcloud that enables exploring and documenting history with the easiest digital tools.",
        image: "/images/abidos.png",
        videoUrl: "",
    },
    {
        id: '14',
        name: "Mohammed Ali Castle",
        location: "Cairo, Egypt",
        category: "Heritage",
        industry: "Monumental Architectural Heritage",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud"],
        challange: "A monumental architectural building that included thick, irregular stone walls, varying floor levels, arches and complex spaces like a maze that are difficult to align and document using the traditional surveying methods.",
        solution: "We used our scanners that capture the exact shape of the space and created a colorized pointcloud that shows all the details, stone textures and enables us walk through history and measure every inch with no issue.",
        image: "/images/mohamedalimosque.png",
        videoUrl: "",
    },
    {
        id: '15',
        name: "Ministry of Finance",
        location: "Cairo, Egypt",
        category: "Architecture",
        industry: "Architecture",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud"],
        challange: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/ministryfinance.png",
        videoUrl: "",
    },
    {
        id: '16',
        name: "Shark Educational Building",
        location: "Cairo, Egypt",
        category: "Architecture",
        industry: "Architecture",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud"],
        challange: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/sharkeducational.png",
        videoUrl: "",
    },
    {
        id: '17',
        name: "Tanta University",
        location: "Tanta, Egypt",
        category: "Architecture",
        industry: "Architecture",
        // client: "Hill International",
        services: ["3D Scanning"],
        deliverables: ["3D Point Cloud"],
        challange: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution: "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/tantauni.png",
        videoUrl: "",
    },
    {
        id: '18',
        name: "Arabian Cement Factory",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/arabiancement.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '19',
        name: "Lafarge Cement Factory",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/lafarge.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '20',
        name: "MBCC Cement Factory",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/mbcc.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '21',
        name: "mediterranean Sea Platform",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/medsea.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '22',
        name: "Red Sea Platform",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/redsea.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '23',
        name: "Rod El Farag",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/rodelfarag.jpg",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
    {
        id: '24',
        name: "Beni Suef South Valley",
        location: "Cairo, Egypt",
        category: "Industrial",
        industry: "Industrial",
        // client: "UPS",
        services: ["3D Laser Scanning", "Underground Detection"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        challange:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        solution:"lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        image: "/images/benisuefvalley.png",
        videoUrl: "https://www.youtube.com/watch?v=PN7UjfXGw_U",
    },
];