export const projects = [
    {
        id: '1',
        name: "El Morssi Abo El Abbas Mosque",
        nameAr: "مسجد المرسي أبو العباس",
        location: "Alexandria, Egypt",
        locationAr: "الإسكندرية، مصر",
        category: "Heritage",
        industry: "Religious and cultural Heritage",
        industryAr: "تراث ديني وثقافي",
        services: ["3D Laser Scanning"],
        servicesAr: ["المسح الليزري ثلاثي الأبعاد"],
        deliverables: ["Pointcloud", "As-Built 2D drawings"],
        deliverablesAr: ["سحابة نقطية", "رسومات ثنائية الأبعاد كما تم التنفيذ"],
        challange: "Morsi Abl Elabbas mosque domes and walls covered with detailed patterns. Traditional measuring tapes and standard images cannot document them accurately.",
        challangeAr: "قباب وجدران مسجد المرسي أبو العباس مغطاة بزخارف دقيقة. لا يمكن لأشرطة القياس التقليدية والصور العادية توثيقها بدقة.",
        solution: "we used advanced laser scanners that act like a digital eye, captures millions of points per second, ensuring high quality pointcloud that shows every ornament and pieces that needs to be repaired.",
        solutionAr: "استخدمنا ماسحات ليزرية متقدمة تعمل كعين رقمية، تلتقط ملايين النقاط في الثانية، لضمان سحابة نقطية عالية الجودة تُظهر كل زخرفة وكل جزء يحتاج إلى ترميم.",
        image: "/images/almorssimosque.webp",
        videoUrl: "https://youtu.be/dpJrYpAAY-Y?si=IUulk9zMrP3ayk6f",
    },
    {
        id: '2',
        name: "Kingdom of Saudi Arabia Consulate",
        nameAr: "قنصلية المملكة العربية السعودية",
        location: "Cairo, Egypt",
        locationAr: "القاهرة، مصر",
        category: "Heritage",
        industry: "Heritage with national significance",
        industryAr: "تراث ذو أهمية وطنية",
        services: ["Pointcloud", "3D Model", "As-built 2D drawings"],
        servicesAr: ["سحابة نقطية", "نموذج ثلاثي الأبعاد", "رسومات ثنائية الأبعاد كما تم التنفيذ"],
        deliverables: ["3D Point Cloud", "High Detailed 3D Model", "2D AutoCAD Drawings (Site, Plans & Elevations)"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج ثلاثي الأبعاد عالي التفاصيل", "رسومات أوتوكاد ثنائية الأبعاد (الموقع، المخططات، الواجهات)"],
        challange:"An Old heritage building with delicate structure and hard accessibility, also, filled with carvings and ornaments, required conducting surveying for documention and restoration.",
        challangeAr: "مبنى تراثي قديم ذو هيكل دقيق وصعوبة في الوصول إليه، ومليء بالنقوش والزخارف، تطلّب إجراء مسح للتوثيق والترميم.",
        solution:"Using different types of laser scanners to map every inch without physically touching a single ancient stone, capturing the ornaments with high density to show cracks and ornaments to deliver a high quality 3D model and 2D drawings.",
        solutionAr: "باستخدام أنواع مختلفة من الماسحات الليزرية لرسم خرائط كل جزء دون لمس أي حجر أثري، والتقاط الزخارف بكثافة عالية لإظهار الشروخ والتفاصيل، لتقديم نموذج ثلاثي الأبعاد ورسومات ثنائية الأبعاد عالية الجودة.",
        image: "/images/saudiconsulate.webp",
        videoUrl: "",
    },
    {
        id: '3',
        name: "Knauf Gypsum Factory",
        nameAr: "مصنع كناف للجبس",
        location: "Suez, Egypt",
        locationAr: "السويس، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Laser Scanning", "Underground Detection"],
        servicesAr: ["المسح الليزري ثلاثي الأبعاد", "الكشف تحت الأرض"],
        deliverables: ["3D Point Cloud", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج ريفيت ثلاثي الأبعاد متكامل (فوق وتحت الأرض)", "مخططات أوتوكاد ثنائية الأبعاد لجميع أنظمة البنية التحتية بالموقع"],
        challange: "The factory's high-speed conveyor belts and constant vibration from gypsum processing machinery can cause \"noise\" in the point cloud, while airborne gypsum dust particles often reflect the laser, creating distorted data and blurry 3D surfaces.",
        challangeAr: "تتسبب أحزمة النقل عالية السرعة والاهتزاز المستمر من آلات معالجة الجبس في حدوث \"تشويش\" في السحابة النقطية، بينما تعكس جزيئات غبار الجبس المحمولة جوًا شعاع الليزر، مما يؤدي إلى بيانات مشوّهة وأسطح ثلاثية الأبعاد غير واضحة.",
        solution: "We utilize Handheld Mobile Scanning with integrated \"Dust-Filtering\" algorithms. By moving strategically around vibrating equipment and using a \"multi-Pass\" walking strategy, we isolate the stable structural geometry from the environmental noise, ensuring a clean 3D model.",
        solutionAr: "نستخدم المسح المحمول المتنقل مع خوارزميات \"تصفية الغبار\" المدمجة. من خلال التحرك بشكل استراتيجي حول المعدات المهتزة واستخدام استراتيجية مشي \"متعددة المسارات\"، نعزل الهندسة الإنشائية الثابتة عن التشويش البيئي، لضمان نموذج ثلاثي الأبعاد نظيف.",
        image: "/images/knauf.webp",
        videoUrl: "https://youtu.be/vivUsBgLtDE?si=hQ4C7R0Ydw2wnGy-",
    },
    {
        id: '4',
        name: "Movenpick",
        nameAr: "موفنبيك",
        location: "Ain Sokhna, Egypt",
        locationAr: "العين السخنة، مصر",
        category: "Architecture",
        industry: "Architecture",
        industryAr: "معماري",
        services: ["3D Laser Scanning for Documentation and Renovation"],
        servicesAr: ["المسح الليزري ثلاثي الأبعاد للتوثيق والترميم"],
        deliverables: ["3D Revit Model", "2D Drawings for hotel buildings (floor plans, ceiling plans, furniture layouts , sections, site plan)"],
        deliverablesAr: ["نموذج ريفيت ثلاثي الأبعاد", "رسومات ثنائية الأبعاد لمباني الفندق (المخططات الأرضية، مخططات الأسقف، توزيع الأثاث، القطاعات، مخطط الموقع)"],
        challange: "Scanning vast, high-traffic resort areas with traditional tripods is slow and disruptive to guests, while long corridors and open landscapes often cause \"SLAM drift,\" leading to distorted or misaligned 3D data.",
        challangeAr: "يُعد مسح مناطق المنتجع الشاسعة وعالية الحركة بالحوامل الثلاثية التقليدية بطيئًا ومزعجًا للنزلاء، كما أن الممرات الطويلة والمساحات المفتوحة غالبًا ما تسبب \"انحراف SLAM\"، مما يؤدي إلى بيانات ثلاثية الأبعاد مشوّهة أو غير متوافقة.",
        solution: "Using Mobile Handheld Scanning, we capture the entire resort at walking speed during low-traffic hours. We eliminate drift by integrating \"Closed-Loop\" trajectories and physical survey targets to ensure absolute global accuracy.",
        solutionAr: "باستخدام المسح المحمول المتنقل، التقطنا المنتجع بالكامل بسرعة المشي خلال ساعات الحركة المنخفضة. نقضي على الانحراف من خلال دمج مسارات \"الحلقة المغلقة\" ونقاط المسح الفعلية لضمان دقة عالمية مطلقة.",
        image: "/images/movenpick.jpg",
        videoUrl: "https://youtu.be/_kQvM9Tn9nE?si=cWJOqG8DLvLWIJvG",
    },
    {
        id: '5',
        name: "Steel Warehouse",
        nameAr: "مستودع الصلب",
        location: "Ain Sokhna, Egypt",
        locationAr: "العين السخنة، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud", "3D BIM Model with MEP Systems", "2D AutoCAD Drawings (Floor Plan- 4 internal Sections)"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج BIM ثلاثي الأبعاد مع أنظمة الكهروميكانيك", "رسومات أوتوكاد ثنائية الأبعاد (مخطط أرضي - 4 قطاعات داخلية)"],
        challange: "Achieving LOD 400 requires documenting every bolt, plate, and connection with millimeter precision. From a single floor position, the warehouse's dense steel rafters and high-level bracing create \"occlusions\" (blind spots), where the scanner cannot \"see\" the top or back of structural members.",
        challangeAr: "يتطلب تحقيق مستوى تفاصيل LOD 400 توثيق كل مسمار ولوحة ووصلة بدقة الملليمتر. من موضع أرضي واحد، تخلق الروافد الفولاذية الكثيفة والدعامات العلوية في المستودع \"مناطق محجوبة\" لا يستطيع الماسح \"رؤية\" أعلى أو خلف العناصر الإنشائية فيها.",
        solution: "We utilize High-Resolution Terrestrial Laser Scanning (TLS). By creating a dense web of overlapping scans, we eliminate all shadows and provide a high-fidelity point cloud and using of scissor lifts to get unreachable ceiling connections.",
        solutionAr: "نستخدم المسح الليزري الأرضي عالي الدقة (TLS). من خلال إنشاء شبكة كثيفة من عمليات المسح المتداخلة، نقضي على جميع المناطق المحجوبة ونوفر سحابة نقطية عالية الدقة، مع استخدام الرافعات المقصية للوصول إلى وصلات السقف التي يصعب الوصول إليها.",
        image: "/images/steelwarehouse.jpg",
        videoUrl: "https://youtu.be/pnhmCdplAC4?si=J-YSZCXVfJegpFzx",
    },
    {
        id: '6',
        name: "Monorail Station 22",
        nameAr: "محطة المونوريل 22",
        location: "New Administration Capital, Egypt",
        locationAr: "العاصمة الإدارية الجديدة، مصر",
        category: "Architecture",
        industry: "Transportation",
        industryAr: "النقل",
        services: ["3D Scanning", "3D As-Built BIM Modeling"],
        servicesAr: ["المسح ثلاثي الأبعاد", "نمذجة BIM كما تم التنفيذ"],
        deliverables: ["3D Point Cloud", "3D Revit Model for As-Built Concrete and Steel Works"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج ريفيت ثلاثي الأبعاد للأعمال الخرسانية والمعدنية كما تم تنفيذها"],
        challange: "Scanning massive, elevated transit stations with complex steel structures and a lot of high scaffolding creates \"blind spots\" and \"SLAM drift\", where the long, repetitive geometry of the station leads to misaligned 3D data and cumulative accuracy errors.",
        challangeAr: "يؤدي مسح محطات النقل الضخمة المرتفعة ذات الهياكل الفولاذية المعقدة والسقالات العالية إلى \"مناطق محجوبة\" و\"انحراف SLAM\"، حيث تؤدي الهندسة الطويلة والمتكررة للمحطة إلى بيانات ثلاثية الأبعاد غير متوافقة وأخطاء دقة تراكمية.",
        solution: "For the site we used Mobile Handheld Scanning to capture all levels at walking speed. To ensure structural precision, we lock the mobile data to a GCP network and for the office we manually deleted the scaffolding to ensure accurate modeling and guaranteeing millimeter accuracy.",
        solutionAr: "للموقع استخدمنا المسح المحمول المتنقل لالتقاط جميع المستويات بسرعة المشي. لضمان الدقة الإنشائية، نربط البيانات المتنقلة بشبكة نقاط تحكم أرضية، وفي المكتب قمنا بحذف السقالات يدويًا لضمان نمذجة دقيقة وضمان دقة الملليمتر.",
        image: "/images/monorail.jpg",
        videoUrl: "https://youtu.be/IzZZMLDH9QQ?si=eciPXJsiwmFcDeMk",
    },
    {
        id: '7',
        name: "Alexandria Main Post Office",
        nameAr: "مبنى البريد الرئيسي بالإسكندرية",
        location: "Alexandria, Egypt",
        locationAr: "الإسكندرية، مصر",
        category: "Architecture",
        industry: "Architecture",
        industryAr: "معماري",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["3D Point cloud", "3D Revit model", "2D AutoCAD plans", "FaÃ§ade drawings"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج ريفيت ثلاثي الأبعاد", "مخططات أوتوكاد ثنائية الأبعاد", "رسومات الواجهات"],
        challange: "Extremely narrow alleys and high-density surroundings prevent capturing the full facade from street level. These tight \"canyons\" create steep scanning angles and leave the roof and upper architectural details in \"shadow.\"",
        challangeAr: "تمنع الأزقة الضيقة للغاية والكثافة العالية المحيطة التقاط الواجهة الكاملة من مستوى الشارع. تخلق هذه \"الممرات\" الضيقة زوايا مسح حادة وتترك السقف والتفاصيل المعمارية العلوية في \"الظل\".",
        solution: "We utilize Handheld Mobile Scanning for the perimeter alleys, combined with vantage points from surrounding roofs. This dual-elevation approach eliminates \"blind spots\" and ensures a complete, high-resolution 3D model of the building's entire exterior.",
        solutionAr: "نستخدم المسح المحمول المتنقل للأزقة المحيطة، مقترنًا بنقاط رصد من الأسطح المجاورة. يقضي هذا النهج ثنائي الارتفاع على \"المناطق المحجوبة\" ويضمن نموذجًا ثلاثي الأبعاد كاملاً وعالي الدقة للواجهة الخارجية بالكامل.",
        image: "/images/alexpost.webp",
        videoUrl: "https://youtu.be/yAfXBYu1Ovo?si=i4JDxV3zIsvJssr0",
    },
    {
        id: '8',
        name: "Cotton Bourse Building",
        nameAr: "مبنى بورصة القطن",
        location: "Alexandria, Egypt",
        locationAr: "الإسكندرية، مصر",
        category: "Heritage",
        industry: "Industrial Heritage",
        industryAr: "تراث صناعي",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["Pointcloud", "2D as-built drawings"],
        deliverablesAr: ["سحابة نقطية", "رسومات ثنائية الأبعاد كما تم التنفيذ"],
        challange: "An ancient decaying building that had been neglected with delicate structure, capturing and turning it into clean 2D drawings that a construction team can use is a massive challenge.",
        challangeAr: "مبنى قديم متهالك تم إهماله وله هيكل دقيق، يُعد التقاطه وتحويله إلى رسومات ثنائية الأبعاد نظيفة يمكن لفريق البناء استخدامها تحديًا كبيرًا.",
        solution: "Using different scanners to capture several areas with different accuracies and deliver 2D drawings for the building that provide enough details for making restoration and rehabilitation decisions.",
        solutionAr: "باستخدام ماسحات مختلفة لالتقاط عدة مناطق بدرجات دقة متفاوتة، وتقديم رسومات ثنائية الأبعاد للمبنى توفر تفاصيل كافية لاتخاذ قرارات الترميم وإعادة التأهيل.",
        image: "/images/cottonbourse.jpg",
        videoUrl: "",
    },
    {
        id: '9',
        name: "Davies and Metropolitan Camp",
        nameAr: "معسكرا ديفيز والمتروبوليتان",
        location: "Luxor, Egypt",
        locationAr: "الأقصر، مصر",
        category: "Heritage",
        industry: "Modern Heritage",
        industryAr: "تراث حديث",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["Pointcloud", "3D models", "2D As-built drawings"],
        deliverablesAr: ["سحابة نقطية", "نماذج ثلاثية الأبعاد", "رسومات ثنائية الأبعاد كما تم التنفيذ"],
        challange: "Two buildings build by the American delegation and by the polish delegation for decades, with a complex and irregular shape and floors required full surveying and documentation, A traditional method cannot fulfill this hard mission.",
        challangeAr: "مبنيان شُيّدا على يد البعثتين الأمريكية والبولندية منذ عقود، بشكل غير منتظم ومعقد، تطلّبا مسحًا وتوثيقًا كاملين لم تستطع الطرق التقليدية إنجازهما.",
        solution: "Using laser scanners to see through the complexity and capture each building in one unified pointcloud that allows us create a detailed 3D model and 2D drawings for all elements even the irregular ones and extract any other data needed for documentation.",
        solutionAr: "باستخدام الماسحات الليزرية لتجاوز التعقيد والتقاط كل مبنى في سحابة نقطية موحدة تتيح لنا إنشاء نموذج ثلاثي الأبعاد مفصل ورسومات ثنائية الأبعاد لجميع العناصر حتى غير المنتظمة منها، واستخراج أي بيانات أخرى لازمة للتوثيق.",
        image: "/images/davies.jpg",
        videoUrl: "https://youtu.be/8tky1rSNpDc?si=9gphCmOzJQqg6Tqa",
    },
    {
        id: '10',
        name: "Horse Racing Grandstands at Sporting Club",
        nameAr: "مدرجات سباق الخيل بالنادي الرياضي",
        location: "Alexandria, Egypt",
        locationAr: "الإسكندرية، مصر",
        category: "Heritage",
        industry: "Social/Recreational Heritage",
        industryAr: "تراث اجتماعي/ترفيهي",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["Pointcloud", "3D Model"],
        deliverablesAr: ["سحابة نقطية", "نموذج ثلاثي الأبعاد"],
        challange: "Sporting stadium in Alexandria, A stadium that wasn't just big; it was a complex maze with overlapping multilevels and many stairs, traditional method like measuring tapes or manual scanners were physically impossible to use.",
        challangeAr: "ملعب رياضي بالإسكندرية لم يكن ضخمًا فحسب، بل متاهة معقدة ذات مستويات متعددة متداخلة وسلالم كثيرة، مما جعل استخدام الطرق التقليدية كأشرطة القياس أو الماسحات اليدوية أمرًا مستحيلًا فعليًا.",
        solution: "We didn't just capture this complex 3D puzzle but also created a detailed 3D model. Using Mobile SLAM technology to scan through the building, mapping every detail and capturing all the different levels then using the generated pointcloud to create a 3D digital twin that can be navigated throw to understand the shape and form of this building.",
        solutionAr: "لم نكتفِ بالتقاط هذا اللغز الثلاثي الأبعاد المعقد، بل أنشأنا أيضًا نموذجًا ثلاثي الأبعاد مفصلاً. باستخدام تقنية SLAM المتنقلة لمسح المبنى، ورسم خرائط كل التفاصيل والتقاط جميع المستويات المختلفة، ثم استخدام السحابة النقطية الناتجة لإنشاء توأم رقمي ثلاثي الأبعاد يمكن التجول فيه لفهم شكل وهيئة هذا المبنى.",
        image: "/images/sporting.webp",
        videoUrl: "https://youtu.be/Ht45Tpmc8Yg?si=nAQGKL8SWTZqStpm",
    },
    {
        id: '11',
        name: "Sahuraa Pyramid",
        nameAr: "هرم ساحورع",
        location: "Giza, Egypt",
        locationAr: "الجيزة، مصر",
        category: "Heritage",
        industry: "Archaeological Heritage",
        industryAr: "تراث أثري",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["Pointcloud", "3D Model"],
        deliverablesAr: ["سحابة نقطية", "نموذج ثلاثي الأبعاد"],
        challange: "The excavation is a delicate and fluid process ,ensuring the safety of the structure and the accuracy of the finds is needed, Also, the interior of the pyramid is pitch black and extremely cramped, neither the traditional ways or the heavy big equipment can help monitoring this hard process.",
        challangeAr: "الحفر عملية دقيقة ومتغيرة، تتطلب ضمان سلامة الهيكل ودقة الاكتشافات، كما أن داخل الهرم شديد الظلام وضيق للغاية، ولا يمكن للطرق التقليدية أو المعدات الكبيرة الثقيلة أن تساعد في مراقبة هذه العملية الصعبة.",
        solution: "Using our lightweight, portable 3D Laser scanners that could be carried deep to the pyramid's heart capturing every stone and recording the \"before and after\" , providing the mission with a \"perfect diary\" of their progress and also a 3D model for the inside chambers of the pyramid.",
        solutionAr: "باستخدام ماسحاتنا الليزرية ثلاثية الأبعاد الخفيفة والمحمولة التي يمكن حملها إلى عمق قلب الهرم، التقطنا كل حجر وسجّلنا \"قبل وبعد\"، لنوفر للبعثة \"يوميات مثالية\" لتقدمها ونموذجًا ثلاثي الأبعاد للحجرات الداخلية للهرم.",
        image: "/images/sahuraa.jpg",
        videoUrl: "https://youtu.be/eY5hd3XFbYM?si=UV9Q71ASl2raI6do",
    },
    {
        id: '12',
        name: "College Saint Marc",
        nameAr: "كلية سان مارك",
        location: "Alexandria, Egypt",
        locationAr: "الإسكندرية، مصر",
        category: "Heritage",
        industry: "Institutional Heritage",
        industryAr: "تراث مؤسسي",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["3D Point Cloud", "2D As-Built Drawings"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "رسومات ثنائية الأبعاد كما تم التنفيذ"],
        challange: "A massive Educational institution with busy sechdule ,and high students traffic, surveying for the entire campus and ,a church with highly detailed ornaments could only be ,conducted in one weekend before the bells rang.",
        challangeAr: "مؤسسة تعليمية ضخمة ذات جدول أعمال مزدحم وحركة طلابية كثيفة، ولم يكن بالإمكان إجراء المسح للحرم بأكمله، بما في ذلك كنيسة ذات زخارف بالغة التفصيل، إلا في عطلة نهاية أسبوع واحدة قبل قرع الأجراس.",
        solution: "with good planning everything is possible. with our high-speed ,scanning team, our smart strategy and good coordination, we used multiple ,Laser scanners to scan the whole campus in just one day, then delivered the 2D ,drawings in no time.",
        solutionAr: "مع التخطيط الجيد كل شيء ممكن. بفريق المسح فائق السرعة، واستراتيجيتنا الذكية وتنسيقنا الجيد، استخدمنا ماسحات ليزرية متعددة لمسح الحرم بأكمله في يوم واحد فقط، ثم سلّمنا الرسومات ثنائية الأبعاد في وقت قياسي.",
        image: "/images/saintmarc.webp",
        videoUrl: "https://youtu.be/itjK1ka6jv4?si=vUfNmNV13Sua4vzi",
    },
    {
        id: '13',
        name: "Abydos Temple of Seti I",
        nameAr: "معبد سيتي الأول بأبيدوس",
        location: "Sohag, Egypt",
        locationAr: "سوهاج، مصر",
        category: "Heritage",
        industry: "Sacred Heritage",
        industryAr: "تراث مقدس",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["3D Point Cloud"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد"],
        challange: "A building from the ancient civilization, with many chambers, dark corners, carvings on walls and complex form. Traditional methods and standard photography will take forever to document this ancient masterpiece.",
        challangeAr: "مبنى من الحضارة القديمة، يضم العديد من الحجرات والزوايا المظلمة والنقوش على الجدران وشكلاً معقدًا. ستستغرق الطرق التقليدية والتصوير الفوتوغرافي القياسي وقتًا طويلاً لتوثيق هذه التحفة القديمة.",
        solution: "we conducted the surveying with our high quality laser 3D scanners and SLAM technology to cover every inch and stone with at most speed and delivered a high density colorized pointcloud that enables exploring and documenting history with the easiest digital tools.",
        solutionAr: "أجرينا المسح باستخدام ماسحاتنا الليزرية ثلاثية الأبعاد عالية الجودة وتقنية SLAM لتغطية كل بوصة وحجر بأقصى سرعة، وسلّمنا سحابة نقطية ملونة عالية الكثافة تتيح استكشاف وتوثيق التاريخ بأسهل الأدوات الرقمية.",
        image: "/images/abidos.webp",
        videoUrl: "",
    },
    {
        id: '14',
        name: "Mohammed Ali Castle",
        nameAr: "قلعة محمد علي",
        location: "Cairo, Egypt",
        locationAr: "القاهرة، مصر",
        category: "Heritage",
        industry: "Monumental Architectural Heritage",
        industryAr: "تراث معماري أثري",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["3D Point Cloud"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد"],
        challange: "A monumental architectural building that included thick, irregular stone walls, varying floor levels, arches and complex spaces like a maze that are difficult to align and document using the traditional surveying methods.",
        challangeAr: "مبنى معماري ضخم يضم جدرانًا حجرية سميكة وغير منتظمة، ومستويات أرضية متفاوتة، وأقواسًا ومساحات معقدة أشبه بالمتاهة، يصعب محاذاتها وتوثيقها باستخدام طرق المساحة التقليدية.",
        solution: "We used our scanners that capture the exact shape of the space and created a colorized pointcloud that shows all the details, stone textures and enables us walk through history and measure every inch with no issue.",
        solutionAr: "استخدمنا ماسحاتنا التي تلتقط الشكل الدقيق للمساحة وأنشأنا سحابة نقطية ملونة تُظهر كل التفاصيل وأنسجة الحجر، وتتيح لنا التجول عبر التاريخ وقياس كل بوصة دون أي مشكلة.",
        image: "/images/mohamedalimosque.webp",
        videoUrl: "",
    },
    {
        id: '15',
        name: "Ministry of Finance",
        nameAr: "وزارة المالية",
        location: "Cairo, Egypt",
        locationAr: "القاهرة، مصر",
        category: "Architecture",
        industry: "Architecture",
        industryAr: "معماري",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["2D CAD drawings"],
        deliverablesAr: ["رسومات كاد ثنائية الأبعاد"],
        challange: "The immense scale and repetitive, uniform corridors of modern government buildings often cause \"SLAM Drift,\" where the handheld scanner loses its precise orientation, leading to distorted 3D maps and cumulative spatial errors over long distances.",
        challangeAr: "غالبًا ما يتسبب الحجم الهائل والممرات الموحدة والمتكررة في المباني الحكومية الحديثة في حدوث \"انحراف SLAM\"، حيث يفقد الماسح المحمول اتجاهه الدقيق، مما يؤدي إلى خرائط ثلاثية الأبعاد مشوهة وأخطاء مكانية تراكمية على مسافات طويلة.",
        solution: "We implement a \"Loop Closure\" Strategy with our handheld scanner. By frequently returning to known starting positions and overlapping our walking paths, the SLAM algorithm automatically corrects and locks the geometry, ensuring a consistent and accurate 3D Pointcloud.",
        solutionAr: "نطبّق استراتيجية \"إغلاق الحلقة\" مع ماسحنا المحمول. من خلال العودة المتكررة إلى نقاط البداية المعروفة وتداخل مسارات المشي، تُصحح خوارزمية SLAM الهندسة تلقائيًا وتثبّتها، لضمان سحابة نقطية ثلاثية الأبعاد متسقة ودقيقة.",
        image: "/images/ministryfinance.webp",
        videoUrl: "",
    },
    {
        id: '16',
        name: "East Educational Building",
        nameAr: "المبنى التعليمي الشرقي",
        location: "Alexandria, Egypt",
        locationAr: "الإسكندرية، مصر",
        category: "Architecture",
        industry: "Architecture",
        industryAr: "معماري",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["3D Point cloud"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد"],
        challange: "Educational buildings feature numerous identical and typical offices, long corridors, and multiple stairwells. This \"Geometric Symmetry\" often confuses handheld scanners, causing the SLAM algorithm to \"slip\" or misalign the 3D data between different floor levels.",
        challangeAr: "تتميز المباني التعليمية بالعديد من المكاتب المتطابقة والنمطية، والممرات الطويلة، والعديد من السلالم. غالبًا ما يؤدي \"التناظر الهندسي\" هذا إلى إرباك الماسحات المحمولة، مما يجعل خوارزمية SLAM \"تنزلق\" أو تُخطئ محاذاة البيانات ثلاثية الأبعاد بين مستويات الطوابق المختلفة.",
        solution: "We utilize Visual and Physical Targets placed at key transition points and stairwells. By scanning in a \"closed-loop\" path from floor to floor, the handheld scanner maintains its orientation, ensuring perfect vertical alignment and spatial accuracy.",
        solutionAr: "نستخدم أهدافًا بصرية ومادية موضوعة في نقاط الانتقال الرئيسية والسلالم. من خلال المسح بمسار \"حلقة مغلقة\" من طابق لآخر، يحافظ الماسح المحمول على اتجاهه، مما يضمن محاذاة رأسية مثالية ودقة مكانية.",
        image: "/images/sharkeducational.webp",
        videoUrl: "https://youtu.be/NvpFqg1XGj0?si=KfAQm0AKcLdYHIQQ",
    },
    {
        id: '17',
        name: "Tanta University Facade",
        nameAr: "واجهة جامعة طنطا",
        location: "Tanta, Egypt",
        locationAr: "طنطا، مصر",
        category: "Architecture",
        industry: "Architecture",
        industryAr: "معماري",
        services: ["3D Scanning for Documentation"],
        servicesAr: ["المسح ثلاثي الأبعاد للتوثيق"],
        deliverables: ["3D Point cloud", "3D model"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج ثلاثي الأبعاد"],
        challange: "The intricate Roman-style decorations, deep reliefs, and high-arched cornices create complex \"geometric shadows,\" where a standard scan from the ground misses the fine details hidden within the deep stone carvings and ornate textures.",
        challangeAr: "تخلق الزخارف الرومانية المعقدة، والنقوش الغائرة العميقة، والأفاريز عالية القوس \"ظلالاً هندسية\" معقدة، حيث يفوّت المسح القياسي من الأرض التفاصيل الدقيقة المخفية داخل النقوش الحجرية العميقة والأنسجة الزخرفية.",
        solution: "We utilize High-Density Terrestrial Scanning at close and far proximity, scanning every pillar and decorative element. This multi-angle Stations ensures the scan algorithm captures every Roman detail, producing a complete, high-definition 3D Pointcloud.",
        solutionAr: "نستخدم المسح الأرضي عالي الكثافة من مسافات قريبة وبعيدة، لمسح كل عمود وعنصر زخرفي. تضمن محطات المسح متعددة الزوايا هذه التقاط خوارزمية المسح لكل تفصيلة رومانية، مما ينتج سحابة نقطية ثلاثية الأبعاد كاملة وعالية الدقة.",
        image: "/images/tantauni.webp",
        videoUrl: "",
    },
    {
        id: '18',
        name: "Arabian Cement Factory",
        nameAr: "مصنع الأسمنت العربية",
        location: "Ain Sokhna, Egypt",
        locationAr: "العين السخنة، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Revit Model"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "مخططات أوتوكاد ثنائية الأبعاد", "نموذج ريفيت ثلاثي الأبعاد"],
        challange: "Massive grinding machinery and dense piping networks create extreme vibrations and \"data shadows,\" hiding critical structural connections and making it impossible to capture clear, stable measurements from a single position.",
        challangeAr: "تخلق آلات الطحن الضخمة وشبكات الأنابيب الكثيفة اهتزازات شديدة و\"ظلال بيانات\"، مما يخفي الوصلات الإنشائية الحرجة ويجعل من المستحيل التقاط قياسات واضحة وثابتة من موضع واحد.",
        solution: "We deploy High-Resolution Terrestrial Laser Scanning from multiple elevated platforms. By using vibration-filtering settings and overlapping scan stations, we eliminate noise to capture every pipe and bolt for a complete 3D model.",
        solutionAr: "ننشر المسح الليزري الأرضي عالي الدقة من منصات مرتفعة متعددة. باستخدام إعدادات تصفية الاهتزاز ومحطات مسح متداخلة، نقضي على التشويش لالتقاط كل أنبوب ومسمار لنموذج ثلاثي الأبعاد كامل.",
        image: "/images/arabiancement.webp",
        videoUrl: "",
    },
    {
        id: '19',
        name: "Lafarge Cement Factory",
        nameAr: "مصنع أسمنت لافارج",
        location: "Ain Sokhna, Egypt",
        locationAr: "العين السخنة، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Revit Model"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "مخططات أوتوكاد ثنائية الأبعاد", "نموذج ريفيت ثلاثي الأبعاد"],
        challange: "The massive height and intricate structural density of the preheater tower make it impossible to capture the high-detail connections required for LOD 400 from the ground, as upper-level steelwork and equipment remain hidden in \"data shadows.\"",
        challangeAr: "يجعل الارتفاع الهائل والكثافة الإنشائية المعقدة لبرج التسخين المسبق من المستحيل التقاط الوصلات عالية التفصيل المطلوبة لمستوى LOD 400 من الأرض، حيث تبقى الأعمال الفولاذية والمعدات في المستويات العليا مخفية في \"ظلال البيانات\".",
        solution: "We execute Multi-Level Terrestrial Scanning, placing the scanner on every structural platform from the base to the summit. This overlapping network captures every bolt, plate, and pipe at millimeter precision, providing the high-fidelity data needed for a detailed LOD 400 model.",
        solutionAr: "ننفّذ مسحًا أرضيًا متعدد المستويات، بوضع الماسح على كل منصة إنشائية من القاعدة إلى القمة. تلتقط هذه الشبكة المتداخلة كل مسمار ولوحة وأنبوب بدقة الملليمتر، لتوفير البيانات عالية الدقة اللازمة لنموذج LOD 400 مفصل.",
        image: "/images/lafarge.webp",
        videoUrl: "",
    },
    {
        id: '20',
        name: "MBCC Cement Factory",
        nameAr: "مصنع أسمنت MBCC",
        location: "Beni Sueif, Egypt",
        locationAr: "بني سويف، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد"],
        challange: "Dense scaffolding and constant worker activity during fabrication create massive \"data noise\" and \"occlusions.\" Static positions are often blocked by temporary poles, while worker movement creates \"ghosting\" effects that can blur critical structural connections.",
        challangeAr: "تخلق السقالات الكثيفة والنشاط المستمر للعمال أثناء التصنيع \"تشويشًا كبيرًا في البيانات\" و\"مناطق محجوبة\". غالبًا ما تُحجب المواضع الثابتة بأعمدة مؤقتة، بينما تخلق حركة العمال تأثيرات \"شبحية\" قد تُشوّش الوصلات الإنشائية الحرجة.",
        solution: "We utilize Terrestrial Laser Scanning (TLS) as the primary tool for millimeter-accurate, supplemented by Handheld Mobile Scanning to reach \"blind spots\" behind scaffolding. This hybrid approach allows us to filter out site noise and move around obstructions, ensuring a clean, high-precision 3D model of the preheater structure.",
        solutionAr: "نستخدم المسح الليزري الأرضي (TLS) كأداة أساسية للدقة بالملليمتر، مدعومًا بالمسح المحمول المتنقل للوصول إلى \"المناطق المحجوبة\" خلف السقالات. يتيح لنا هذا النهج الهجين تصفية تشويش الموقع والتحرك حول العوائق، لضمان نموذج ثلاثي الأبعاد نظيف وعالي الدقة لهيكل التسخين المسبق.",
        image: "/images/mbcc.webp",
        videoUrl: "",
    },
    {
        id: '21',
        name: "Mediterranean Sea Gas Platforms",
        nameAr: "منصات الغاز في البحر المتوسط",
        location: "Mediterranean Sea, Egypt",
        locationAr: "البحر المتوسط، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud", "3D Model"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "نموذج ثلاثي الأبعاد"],
        challange: "Offshore platforms are high-vibration, High density of piping systems making it difficult to mount terrestrial scanner and high-risk environments where Salt-Spray Corrosion and reflective stainless-steel piping cause \"laser scattering\", leading to misaligned structural data.",
        challangeAr: "المنصات البحرية بيئات عالية الاهتزاز وذات كثافة عالية من شبكات الأنابيب، مما يجعل تثبيت الماسح الأرضي صعبًا، وبيئات عالية الخطورة حيث يتسبب التآكل الناتج عن رذاذ الملح والأنابيب الفولاذية اللامعة في \"تشتت الليزر\"، مما يؤدي إلى بيانات إنشائية غير متوافقة.",
        solution: "We utilize Handheld Mobile Scanning to quickly capture dense piping networks before salt buildup affects the laser. By using a \"Multiple Loop\" walking path and filtering out high-frequency machinery vibrations in post-processing, we ensure a clean, accurate 3D as-built model for offshore maintenance.",
        solutionAr: "نستخدم المسح المحمول المتنقل لالتقاط شبكات الأنابيب الكثيفة بسرعة قبل أن يؤثر تراكم الملح على الليزر. باستخدام مسار مشي \"متعدد الحلقات\" وتصفية اهتزازات الآلات عالية التردد أثناء المعالجة اللاحقة، نضمن نموذجًا ثلاثي الأبعاد نظيفًا ودقيقًا كما تم تنفيذه لأعمال الصيانة البحرية.",
        image: "/images/medsea.webp",
        videoUrl: "",
    },
    {
        id: '22',
        name: "Red Sea Oil Platform",
        nameAr: "منصة نفط البحر الأحمر",
        location: "Red Sea, Egypt",
        locationAr: "البحر الأحمر، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد"],
        challange: "Offshore platforms feature extreme reflective surfaces (stainless steel and chrome) and constant structural vibration from heavy drilling equipment, which causes \"laser scattering\" and distorted, noisy 3D data.",
        challangeAr: "تتميز المنصات البحرية بأسطح شديدة الانعكاس (الفولاذ المقاوم للصدأ والكروم) واهتزاز إنشائي مستمر من معدات الحفر الثقيلة، مما يسبب \"تشتت الليزر\" وبيانات ثلاثية الأبعاد مشوهة وصاخبة.",
        solution: "We utilize High-Resolution Terrestrial Scanning with specialized \"Vibration-Filtering\" and \"Reflective Surface\" settings. By establishing a dense network of stable scan stations, we eliminate data noise to provide a clean, millimeter-accurate 3D Pointcloud.",
        solutionAr: "نستخدم المسح الأرضي عالي الدقة بإعدادات متخصصة لـ\"تصفية الاهتزاز\" و\"الأسطح العاكسة\". من خلال إنشاء شبكة كثيفة من محطات المسح الثابتة، نقضي على تشويش البيانات لتوفير سحابة نقطية ثلاثية الأبعاد نظيفة ودقيقة بالملليمتر.",
        image: "/images/redsea.webp",
        videoUrl: "",
    },
    {
        id: '23',
        name: "Water Pump Station - Rod El Farag",
        nameAr: "محطة رفع المياه - روض الفرج",
        location: "Cairo, Egypt",
        locationAr: "القاهرة، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Laser Scanning", "Underground Detection"],
        servicesAr: ["المسح الليزري ثلاثي الأبعاد", "الكشف تحت الأرض"],
        deliverables: ["3D Point Cloud", "2D AutoCAD Plans", "3D Integrated Revit Model (Above & Underground)", "2D AutoCAD Plans for All Infrastructure Systems in Site"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد", "مخططات أوتوكاد ثنائية الأبعاد", "نموذج ريفيت ثلاثي الأبعاد متكامل (فوق وتحت الأرض)", "مخططات أوتوكاد ثنائية الأبعاد لجميع أنظمة البنية التحتية بالموقع"],
        challange: "Water stations feature complex, overlapping piping networks both above and underground. Capturing these interconnected systems is difficult because narrow pump rooms and buried infrastructure create \"access voids,\" making it hard to align surface structures with sub-surface utilities.",
        challangeAr: "تتميز محطات المياه بشبكات أنابيب معقدة ومتداخلة فوق وتحت الأرض. يصعب التقاط هذه الأنظمة المترابطة بسبب غرف المضخات الضيقة والبنية التحتية المدفونة التي تخلق \"فراغات وصول\"، مما يجعل من الصعب محاذاة الهياكل السطحية مع المرافق تحت السطحية.",
        solution: "We utilize Handheld Mobile Scanning to move fluidly through tight spaces and stairwells in continuous loops. This \"Walk-Through\" method ensures 100% coverage of complex piping, providing the seamless data needed to build the Integrated Revit Model and detailed 2D AutoCAD infrastructure plans.",
        solutionAr: "نستخدم المسح المحمول المتنقل للتحرك بسلاسة عبر المساحات الضيقة والسلالم في حلقات متواصلة. تضمن طريقة \"المشي المتصل\" هذه تغطية كاملة 100% للأنابيب المعقدة، مما يوفر البيانات السلسة اللازمة لبناء نموذج ريفيت المتكامل والمخططات التفصيلية للبنية التحتية بصيغة أوتوكاد ثنائية الأبعاد.",
        image: "/images/rodelfarag.jpg",
        videoUrl: "https://youtu.be/438vQEb-Ci0?si=17D6XCnloKG7QC5J",
    },
    {
        id: '24',
        name: "SVCC Cement Factory",
        nameAr: "مصنع أسمنت SVCC",
        location: "Beni Sueif, Egypt",
        locationAr: "بني سويف، مصر",
        category: "Industrial",
        industry: "Industrial",
        industryAr: "صناعي",
        services: ["3D Scanning"],
        servicesAr: ["المسح ثلاثي الأبعاد"],
        deliverables: ["3D Point Cloud"],
        deliverablesAr: ["سحابة نقطية ثلاثية الأبعاد"],
        challange: "The extreme heat radiation and atmospheric haze around the kiln and cooler create \"mirage effects\" that distort laser beams, while the vertical complexity of the preheater causes massive \"data shadows\" in the structural steel and ducting.",
        challangeAr: "يخلق الإشعاع الحراري الشديد والضباب الجوي حول القمينة والمبرّد \"تأثيرات سراب\" تُشوّه أشعة الليزر، بينما يتسبب التعقيد الرأسي لبرج التسخين المسبق في \"ظلال بيانات\" ضخمة في الهيكل الفولاذي وأنظمة القنوات.",
        solution: "We utilize High-Resolution Terrestrial Scanning with heat-shielded equipment and \"Atmospheric Compensation\" settings. By scanning during scheduled maintenance shutdowns and using multi-level stationing, we capture the exact alignment of the kiln and the full structural density of the preheater.",
        solutionAr: "نستخدم المسح الأرضي عالي الدقة بمعدات معزولة حراريًا وإعدادات \"تعويض جوي\". من خلال المسح أثناء فترات التوقف المجدولة للصيانة واستخدام المحطات متعددة المستويات، نلتقط المحاذاة الدقيقة للقمينة والكثافة الإنشائية الكاملة لبرج التسخين المسبق.",
        image: "/images/benisuefvalley.webp",
        videoUrl: "",
    },
];
